### PR TITLE
Update build-openblas.sh

### PR DESCRIPTION
**Pull request by pcagas**
Updating openBLAS to a newer version helps with the issue of not detecting some hardware (at least on my new laptop). I'm running with this on my Ubuntu laptop and everything seems to be okay.

### CODE REVIEW

**Comment by manauref** [comment]
@pcagas I tried building in this branch on Perlmutter by
- removing my old gkylsoft/OpenBlas* directories
- running the mkdeps machine file
- running the configure machine file
- doing make -j 32 install

and I encountered this error:

```
zero/mat.c:18:11: fatal error: cblas.h: No such file or directory
   18 | # include <cblas.h>
      |           ^~~~~~~~~
compilation terminated.
make: *** [Makefile:131: cuda-build/zero/mat.c.o] Error 1
make: *** Waiting for unfinished jobs....
```

When you did this, did you try this with a clean or new gkylsoft and/or build/cuda-build?

**Comment by manauref** [comment]
I see the problem. When downloading OpenBLAS on Perlmutter with
```
curl -L https://github.com/xianyi/OpenBLAS/releases/download/v0.3.15/OpenBLAS-0.3.23.tar.gz > OpenBLAS-0.3.23.tar.gz
```
it produces the file ```OpenBLAS-0.3.23.tar.gz```, but the next step
```
gunzip -f OpenBLAS-0.3.23.tar.gz
```
yields
```
gzip: OpenBLAS-0.3.23.tar.gz: not in gzip format
```

I don't know how to fix this yet.

**Comment by manauref** [comment]
i see, there's an error in the curl command, it still has 3.15 in it. I'll fix and try it.

**Comment by pcagas** [comment]
@manauref oh, that is embarrassing, my bad!

**Comment by pcagas** [comment]
To answer the question, yes, it was a clear install. I couldn't install gkyl at all before changing the openBLAS version.

**Pull request merged**
