### PR TITLE
GK comms functions and further standardization of reg tests

### PR DESCRIPTION
**Pull request by manauref**
Create new gyrokinetic_comms functions which package the comm creation for our input tests. Benefits:
1. Removes repetitive 80-100 lines of code from each input file.
2. Reduce the risk of someone making a mistake in this logic in future input files.
3. When we parallelize species, we'll be able to add that additional feature to these new functions with minor modifications to input files.

Also standardize the way number of cells are set in regression tests. This makes it easier to make changes across all reg tests, again reduces the changes of introducing mistakes, etc.

I ran gk_sheath_2x2v on 1 and 2 CPUs or GPUs, reproducing expected results. I also compiled and ran (for 3 steps) every reg test, and through this found there was a bug in the vlasov_lte app for gk neutral species, which is fixed here.

### CODE REVIEW

**Review by akashukla — APPROVED** [review]
Looks good to me based on reviewing the changes in apps/ and a few regression tests I am familiar with. I have made sloppy mistakes creating the comms for reg tests/simulations, so I think this is helpful.

**Comment by ammarhakim** [comment]
Don’t merge yet. I will do it tomorrow Sent from my iPhoneOn May 30, 2024, at 7:11 PM, akashukla ***@***.***> wrote:﻿
@akashukla approved this pull request.

Looks good to me based on reviewing the changes in apps/ and a few regression tests I am familiar with. I have made sloppy mistakes creating the comms for reg tests/simulations, so I think this is helpful.

**Comment by manauref** [comment]
For the sake of discussion (FYI @JunoRavin), adding num_species to the input file context, and passing it to these functions, the creation of the conf-space communicator could be made species-parallelization aware (I think the species comm could/would be created inside the GK app).

I thought about doing it here, even if we are not yet using the species comm, but one thing I was unsure about we should discuss is how to handle the split between gk_species and gk_neut_species.

**Comment by dingyunl** [comment]
I'm trying to run a longer regression test with the asdex geometry and I need the parallelization feature in the input file. Is this branch about ready to merge?

**Comment by ammarhakim** [comment]
@dingyunl the regression tests are already easy to parallelize. This just wraps a few things to make it cleaner. You do not need to wait for this.

**Pull request merged**
