### PR TITLE
Twist-shift BC updater

### PR DESCRIPTION
**Pull request by manauref**
This is an implementation of the twist-shift (TS) boundary condition (BC) for 5D gyrokinetics. The original algorithms is described in M. Francisquez, et al. CPC 298 (2024) 109109, but we (@akashukla, @jRoeltgen and I) have implemented a simplified version of it, see issue #384  (in particular the comment on July 31 2024), and the comments at the top of zero/bc_twistshift.c. I reproduce a couple of these comments here:
1. Unlike the procedures described in M. Francisquez, et al. CPC 298 (2024) 109109, all subcell integrals are now done with variable y limits. This is possible once we realize that figure 4 is not drawn accurately; the blue lines should be separated by Delta y at all points.
2. This updater only works on 5D distributions. Likely only minor changes are needed to make it work in other dimensions.
3. 99% of the code is written to support a BC, a shift and shear in any direction. Maybe the only thing that needs to change is the permutted range and its use.

There is a unit test, which runs on CPUs and GPUs, and with which I've been able to reproduce figures 6, 9 and 11 from the paper. I've also confirmed the conversation property shown in figure 16a.

The way this works is:
1. One must first apply regular periodicity (outside of this updater).
2. Pass the distribution to this updater, and it will twist-shift the distribution that was previously in the ghost cell (in-place).

See issue #384 for possible improvements, which we should only pursue after some simulations have been done.

### CODE REVIEW

**Comment by tnbernard** [comment]
I would like to see a 5D 'clopen' simulation tested before merging, and I am happy to help with this.

**Comment by manauref** [comment]
My logic was to PR the updater alone here. The clopen-specific stuff will come in a separate PR (since that will mostly involve changes to the app).

If you guys want clopen to happen here that's fine by me, but it'll make this PR bigger.

**Comment by tnbernard** [comment]
That makes sense to wait for clopen. What about Fig. 17 in your 2024 paper? Are you able to reproduce that?

**Comment by manauref** [comment]
We are not able to reproduce figure 17 because that requires a delta-f
solver we had in g2 but not in g0. It would take a bit of work (probably a
new app) to do that.

**Review by tnbernard — APPROVED** [review]

**Review by ammarhakim — APPROVED** [review]
This is ready to merge.

**Pull request merged**
