### PR TITLE
Make parts of project_on_basis and eval_on_nodes public

### PR DESCRIPTION
**Pull request by manauref**
This is mainly so we can call parts of it from g2. The part that actually evaluates the function at nodes in g2 is still done in g2.

Also add some unit tests.

### CODE REVIEW

**Comment by ammarhakim** [comment]
In the header file for proj_on_basis you have a typedef to the struct. After that the explicit declarations like:

struct gkyl_proj_on_basis *up

are not needed and can be replaced with

gkyl_proj_on_basis *up

I am not sure why you have added the struct keyword to every method in the header when they are not really needed.

**Comment by ammarhakim** [comment]
Storing grid by reference is not correct and we can't allow that. It is a major and serious risk. Please point out the valgrind error and we can debug. Do not store POD (plain-old-data) objects by reference.

**Comment by manauref** [comment]
@ammarhakim 
here's a reproduction of the valgrind error
```
[manaurer@stellar-intel gkylzero]$ valgrind --leak-check=full ./build/unit/ctest_proj_on_basis test_1
==3769160== Memcheck, a memory error detector
==3769160== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==3769160== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==3769160== Command: ./build/unit/ctest_proj_on_basis test_1
==3769160==
Test test_1...                                  vex amd64->IR: unhandled instruction bytes: 0x62 0xF1 0xFE 0x8 0x6F 0x13 0x4D 0x63 0x46 0x14
vex amd64->IR:   REX=0 REX.W=0 REX.R=0 REX.X=0 REX.B=0
vex amd64->IR:   VEX=0 VEX.L=0 VEX.nVVVV=0x0 ESC=NONE
vex amd64->IR:   PFX.66=0 PFX.F2=0 PFX.F3=0
==3769160== valgrind: Unrecognised instruction at address 0x4f1b76a.
==3769160==    at 0x4F1B76A: gkyl_proj_on_basis_inew (proj_on_basis.c:45)
==3769160==    by 0x4F1C00E: gkyl_proj_on_basis_new (proj_on_basis.c:28)
==3769160==    by 0x40337C: test_1 (ctest_proj_on_basis.c:28)
==3769160==    by 0x403971: test_do_run_ (acutest.h:1012)
==3769160==    by 0x401A52: test_run_ (acutest.h:1183)
==3769160==    by 0x401A52: main (acutest.h:1735)
==3769160== Your program just tried to execute an instruction that Valgrind
==3769160== did not recognise.  There are two possible reasons for this.
==3769160== 1. Your program has a bug and erroneously jumped to a non-code
==3769160==    location.  If you are running Memcheck and you just saw a
==3769160==    warning about a bad jump, it's probably your program's fault.
==3769160== 2. The instruction is legitimate but Valgrind doesn't handle it,
==3769160==    i.e. it's Valgrind's fault.  If you think this is the case or
==3769160==    you are not sure, please let us know and we'll try to fix it.
==3769160== Either way, Valgrind will now raise a SIGILL signal which will
==3769160== probably kill your program.
==3769160==
==3769160== Process terminating with default action of signal 4 (SIGILL)
==3769160==  Illegal opcode at address 0x4F1B76A
==3769160==    at 0x4F1B76A: gkyl_proj_on_basis_inew (proj_on_basis.c:45)
==3769160==    by 0x4F1C00E: gkyl_proj_on_basis_new (proj_on_basis.c:28)
==3769160==    by 0x40337C: test_1 (ctest_proj_on_basis.c:28)
==3769160==    by 0x403971: test_do_run_ (acutest.h:1012)
==3769160==    by 0x401A52: test_run_ (acutest.h:1183)
==3769160==    by 0x401A52: main (acutest.h:1735)
==3769160==
==3769160== HEAP SUMMARY:
==3769160==     in use at exit: 14,848 bytes in 24 blocks
==3769160==   total heap usage: 24 allocs, 0 frees, 14,848 bytes allocated
==3769160==
==3769160== 272 bytes in 1 blocks are definitely lost in loss record 13 of 24
==3769160==    at 0x4C38135: malloc (vg_replace_malloc.c:381)
==3769160==    by 0x4EFB34B: gkyl_malloc_ (alloc.c:46)
==3769160==    by 0x4F1B763: gkyl_proj_on_basis_inew (proj_on_basis.c:43)
==3769160==    by 0x4F1C00E: gkyl_proj_on_basis_new (proj_on_basis.c:28)
==3769160==    by 0x40337C: test_1 (ctest_proj_on_basis.c:28)
==3769160==    by 0x403971: test_do_run_ (acutest.h:1012)
==3769160==    by 0x401A52: test_run_ (acutest.h:1183)
==3769160==    by 0x401A52: main (acutest.h:1735)
==3769160==
==3769160== LEAK SUMMARY:
==3769160==    definitely lost: 272 bytes in 1 blocks
==3769160==    indirectly lost: 0 bytes in 0 blocks
==3769160==      possibly lost: 0 bytes in 0 blocks
==3769160==    still reachable: 14,576 bytes in 23 blocks
==3769160==         suppressed: 0 bytes in 0 blocks
==3769160== Reachable blocks (those to which a pointer was found) are not shown.
==3769160== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==3769160==
==3769160== For lists of detected and suppressed errors, rerun with: -s
==3769160== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Illegal instruction
```

**Comment by ammarhakim** [comment]
This looks like a problem with the opcode and not memory issues (which are also present, though it could be misleading due to the SIG): 

Illegal opcode at address 0x4F1B76A

Can you revert your last commit to the branch so I can test when I get the chance?

**Comment by manauref** [comment]
reopening PR after reverting last commit.
Stellar-intel valgrind still says there's an issue, even after make install, removing the lib, and making again. But maybe @ammarhakim's valgrind is better

**Pull request merged**
