### PR TITLE
Maxwellian fix

### PR DESCRIPTION
**Pull request by dingyunl**
An updater zero/correct_maxwellian_gyrokinetic.c (together with its header file zero/gkyl_correct_maxwellian_gyrokinetic.h) and a unit test unit/ctest_correct_maxwellian_gyrokinetic.c were created to fix the maxwellian. They can run on both cpu and gpu.

### CODE REVIEW

**Comment by manauref** [comment]
@dingyunl your PR says this primarily implements the correct_maxwellian updater. Yet this PR changes 13 files, many of which are unrelated to your work, and some are changes to build files that will break the build for other people. I suggest you undo these changes and only merge the relevant files.

Perhaps this is because you started this branch from some other branch that hasn't been merged into main. Where did you branch off of to create maxwellian-fix?

**Comment by manauref** [comment]
@dingyunl if you created this branch from one of the gpuHackathon_2023 branches, another option is to merge your branch into gpuHackathon_2023 instead of merging into main.

**Comment by dingyunl** [comment]
> @dingyunl your PR says this primarily implements the correct_maxwellian updater. Yet this PR changes 13 files, many of which are unrelated to your work, and some are changes to build files that will break the build for other people. I suggest you undo these changes and only merge the relevant files.
> 
> Perhaps this is because you started this branch from some other branch that hasn't been merged into main. Where did you branch off of to create maxwellian-fix?

I can't remember exactly but most likely it was created from the main.

**Comment by ammarhakim** [comment]
We need to fix some issues before accepting this PR.

**Comment by dingyunl** [comment]
> @dingyunl if you created this branch from one of the gpuHackathon_2023 branches, another option is to merge your branch into gpuHackathon_2023 instead of merging into main.

**Pull request closed without merging**
